import type { NextPage } from 'next'
import { Button } from 'antd';

import Head from 'next/head'
import styles from '../styles/Home.module.css';
import home from '../styles/Home.module.less';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className={`${home.container} `}>
              <div className={"animate__animated animate__backInLeft"}> hello, react-website-basic </div>
          </div>
          <Button>Great!</Button>
      </main>
    </div>
  )
}

export default Home
